# Generated by Django 4.1.13 on 2024-05-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDesigner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answer_audio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='question_audio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
